export const FETCH_CONVERSATION = "FETCH_CONVERSATION"
export const FETCH_CONVERSATION_START = "FETCH_CONVERSATION_START"
export const FETCH_CONVERSATION_SUCCESS = "FETCH_CONVERSATION_SUCCESS"
export const FETCH_CONVERSATION_FAILURE = "FETCH_CONVERSATION_FAILURE"

export const PUSH_CONVERSATION = "PUSH_CONVERSATION"