export const FETCH_SESSION_START = 'FETCH_SESSION_START'
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE'
export const FETCH_SESSION = 'FETCH_SESSION'